### ISSUE TITLE
Type 10_LA

### ISSUE THREAD

**Issue by sm3604** [mandli/intro-numerical-methods#13]
In "Example: Vandermonde Matrix," I believe the y matrix should be y1, y2 ... ym.

**Comment by sm3604** [comment]
In the eigenspace example, there is a missing '$' causing 'A trick that works most of the time is to normalize each vector such that the first entry is 1 ($v_1 = 1)' to appear.

**Comment by sm3604** [comment]
A little further down there is a missing parenthesis in the first equation following "and just to make sure"

**Comment by mandli** [comment]
Thanks!
