### ISSUE TITLE
Mistake and typoes in Backward Substitution, Solving Ax=b, 15_LA_gaussian

### ISSUE THREAD

**Issue by yeejoh** [mandli/intro-numerical-methods#16]
In Backward Substitution, Solving Ax=b, 15_LA_gaussian, it writes:
> Backwards substitution requires us to move from the last row of $U$ and move upwards.  We can consider again the general $i$th row with
> $$
>     U_{i,i} x_i + U_{i,i-1} x_{i-1} + \ldots + U_{i,m-1} x_{m-1} + U_{i,m} x_m = y_i
> $$
> noting that we are using the fact that the matrix $L$ has 1 on its diagonal. We can now solve for $y_i$ as
> $$
>     x_i = \frac{1}{U_{i,i}} \left( y_i - ( U_{i,i-1} x_{i-1} + \ldots + U_{i,m-1} x_{m-1} + U_{i,m} x_m) \right )
> $$

1. Both equations have index mistake ($U_{i,i-1} x_{i-1}$), which should be
$$U_{i,i} x_i + U_{i,i+1} x_{i+1} + \ldots + U_{i,m-1} x_{m-1} + U_{i,m} x_m = y_i$$,
$$x_i = \frac{1}{U_{i,i}} \left( y_i - ( U_{i,i+1} x_{i+1} + \ldots + U_{i,m-1} x_{m-1} + U_{i,m} x_m) \right )$$.

2. Matrix $L$ has nothing to do with backwards substitution. Noting that the matrix $L$ has 1 on its diagonal is unnecessary.

3. The second sentence of ones between two equations should be
> We can now solve for $x_i$ as ...

**Comment by mandli** [comment]
Thanks, (1) has been fixed and (2) and (3) was clearly a copy-paste error (I should have proof read).

**Comment by mandli** [comment]
This has been addressed now in commit https://github.com/mandli/intro-numerical-methods/commit/74378de11c3146b1999e55a8f6a68768dd0113f9#diff-7cf2daec2ce73ce6343d2c99819e2a16
