### ISSUE TITLE
Maybe not a mistake in 04_error?

### ISSUE THREAD

**Issue by kswanberg** [mandli/intro-numerical-methods#25]
In the code for the "2-digit precision base 2 system" in the 04_error notebook, we see the system defined as follows: 
 
axes.plot( (d1 + d2 * 0.1) * 2**E, 0.0, 'r+', markersize=20)
axes.plot(-(d1 + d2 * 0.1) * 2**E, 0.0, 'r+', markersize=20)
 
Shouldn't the 0.1 be 0.5, since this is binary and not decimal (or maybe I am missing something)?

**Comment by mandli** [comment]
Yeah, that was a typo.
