### ISSUE TITLE
A probable mistake in differentiation at Asymptotic Convergence of Newton's Method

### ISSUE THREAD

**Issue by yeejoh** [mandli/intro-numerical-methods#3]
At 5 Root Finding and Optimization, Asymptotic Convergence of Newton's Method
> ... Let `$g(x) = x - \frac{f(x)}{f'(x)}$`, then
> ...
> What about `$g'(x^*)$` though:
> `$$g'(x) = 1 - \frac{f'(x)}{f'(x)} + \frac{f(x)}{f''(x)}$$`
> which simplifies when evaluated at `$x = x^*$` to
> `$$g'(x^*) = \frac{f(x^*)}{f''(x^*)} = 0$$`
> ...

Since the Quotient Rule, `$$\left ( \frac{u}{v} \right )' = \frac{u' v - v' u}{v^2}$$`,

I think it should be `$$g'(x) = 1 - \frac{f'(x) f'(x) - f(x) f''(x)}{f'^2(x)} = 1 - 1 + \frac{f(x) f''(x)}{f'^2(x)}$$`.

Nonetheless, `$$g'(x^*) = \frac{f(x^*) f''(x^*)}{f'^2(x^*)} = 0$$`, `$$g''(x^*) = \frac{f''(x^*)}{f'(x^*)}$$`, so it won't effect the following result.

**Comment by mandli** [comment]
There is a mistake as you said, there is a missing extra $1/f'(x)$ term.  Thanks for pointing this out!
