### ISSUE TITLE
Error in Bracketing Algorithm- Basic Idea

### ISSUE THREAD

**Issue by dragonyanglong** [mandli/intro-numerical-methods#32]
I saw you revised this part before, but it did not look correct.

If $f(x_2) &lt; f(x_1)$ then we know the minimum is between $x_0$ and $x_2$.
If $f(x_2) &gt; f(x_1)$ then we know the minimum is between $x_1$ and $x_3$.

Should not the sign be reversed?

**Comment by mandli** [comment]
Dang, I changed this so that is was correct but then went back and changed my indices incorrectly.  Thanks for catching this.  You get a sticker.
