### ISSUE TITLE
error in 09_ODE_ivp_part1

### ISSUE THREAD

**Issue by dragonyanglong** [mandli/intro-numerical-methods#36]
In "Example: 4-stage Runge-Kutta Method"

    y_2 = u_4[n] + 0.5 * delta_t * f(t_n + 0.5 * delta_t, y_1)
    y_3 = u_4[n] + 0.5 * delta_t * f(t_n + 0.5, y_2)

**Comment by mandli** [comment]
Fixed, thanks!
