### ISSUE TITLE
09_ODE_ivp_part1.ipynb

### ISSUE THREAD

**Issue by massma** [mandli/intro-numerical-methods#45]
I think there is a typo in the lecture, in the "Truncation Error for Multi-Step Methods" section. 

In the last expression I *think* the general form for the q-ith term is miss-written. A summation seems missing, and I also think that the 1/q! term should not be multiplying both the \alpha and \beta terms (it should just be multiplying the \alpha term). For example:

\Delta t^{q - 1} \left (\frac{1}{q!} \left(j^q \alpha_j - \frac{1}{(q-1)!} j^{q-1} \beta_j \right) \right) u^{(q)}(t_n)

should be:

\Delta t^{q - 1} \left( \sum^r_{j=0} \left (\frac{1}{q!} j^q \alpha_j - \frac{1}{(q-1)!} j^{q-1} \beta_j \right) \right) u^{(q)}(t_n)

**Comment by mandli** [comment]
I think I fixed this now, can you check?

**Comment by massma** [comment]
That looks right to me, closing issue.
