### ISSUE TITLE
Possible typo in interpolation slides

### ISSUE THREAD

**Issue by sm3604** [mandli/intro-numerical-methods#5]
![2015-10-08 16_58_31](https://cloud.githubusercontent.com/assets/7840387/10379712/d991887a-6ddd-11e5-8213-9beba606b198.png)
In the above picture, shouldn't their be coefficients of x and x^2 in the bottom matrix matching the equations above it?

**Comment by mandli** [comment]
You are correct, will make a correction.

**Comment by mandli** [comment]
The notes have been fixed, thanks again for catching this.
