### ISSUE TITLE
Error in Golden Search Derivation

### ISSUE THREAD

**Issue by xl2604** [mandli/intro-numerical-methods#50]
c = a^2 / b → a / b = a^2 / [b (b - a^2 / b)]
                      a / b = a^2 / (b^2 - a^2)
(there's an extra factor of 1 / b^2 in the notes)

**Comment by mandli** [comment]
I have fixed this specific issue but I believe the source I have taken this from may have an inconsistency in the derivation.  I have rewritten this section and now have a new version up and would appreciate feedback from @x94carbone and @xl2604 to see if this answers your questions before we close this issue.

**Comment by x94carbone** [comment]
It looks good to me. The usage of the golden ratio and pseudo-code algorithm are correct to my knowledge. Thanks for addressing this! What do you think @xl2604?

**Comment by xl2604** [comment]
Having checked the new version carefully. Looks good to me too!

**Comment by mandli** [comment]
Great!  Thanks to you both for making the notes better.
