### ISSUE TITLE
05_root_finding_optimization

### ISSUE THREAD

**Issue by x94carbone** [mandli/intro-numerical-methods#51]
In the block containing

`x = [0.2, None, None, 0.5]`

`x[1] = x[3] - phi * (x[3] - x[0])`

`x[2] = x[0] + phi * (x[3] - x[0])`

I believe there is an error. The golden ratio phi is defined as 1.61803, but if that is true, then we should be dividing by the golden ratio, not multiplying by it. The code happens to work because the interval chosen in the notes is small enough such that x[1] and x[2] happen to fall within the interval. Making the interval larger will prevent this from happening and the brackets will diverge away. 

Something along these lines was mentioned in class, but I figured I'd raise the potential issue just to be thorough.

**Comment by xl2604** [comment]
Yep, there is an inconsistency issue here.
In the notes, it writes golden ratio is b / a
> phi = (numpy.sqrt(5.0) - 1.0) / 2.0
x[1] = x[3] - phi * (x[3] - x[0])
x[2] = x[0] + phi * (x[3] - x[0])

I think if golden ratio is b/a (which is 1.618)
Then the code should be
> phi = (numpy.sqrt(5.0) + 1.0) / 2.0
x[1] = x[3] -  (x[3] - x[0]) / phi
x[2] = x[0] + (x[3] - x[0]) / phi

On the other hand, if we consider a/b as golden ratio (which is 0.618)
Then the code part is right, only need to correct the markdown above the code.

**Comment by mandli** [comment]
I am going to mark this is a repeat of #50.  Thanks for the report!
