### ISSUE TITLE
Problems with two equations in Computing Order of Convergence, Differentiation

### ISSUE THREAD

**Issue by yeejoh** [mandli/intro-numerical-methods#6]
In 7_Differentiation, Examples, Example 1: 1st order Forward and Backward Differences, Computing Order of Convergence part, there are two equations:
e(Δx) = Δx^n + b
log e(Δx) = n logb logΔx

However, I don't think log e(Δx) equals that.
If I change the e(Δx), equations seem to be correct then.
e(Δx) = b Δx^n
log e(Δx) = logb + n logΔx
And the following plot supports that.

**Comment by mandli** [comment]
Technically I think the expression should be $e(\Delta x) = b \Delta x^n + c$ perhaps but I think your expression is more appropriate.  Will make the change.

**Comment by mandli** [comment]
Fixed.
