### ISSUE TITLE
Possible typo in quadrature lecture

### ISSUE THREAD

**Issue by sm3604** [mandli/intro-numerical-methods#7]
Under 'Newton-Cotes Quadrature,' the lecture contains the phrase: 
"evaluate f(x) at these points and exactly integrate the interpolating polynomial exactly."

was this intended?

**Comment by mandli** [comment]
You mean besides the poor English?  Newton-Cotes assumes that the points are equally spaced across the partition and integrates the resulting interpolating polynomial exactly (the interpolating polynomial here) to generate the quadrature rule.

**Comment by mandli** [comment]
Typo fixed.
